import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceParty",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("party_type", models.CharField(choices=[("INDIVIDUAL", "Individual"), ("ENTITY", "Entity")], db_index=True, max_length=20)),
                ("display_name", models.CharField(max_length=255)),
                ("legal_name", models.CharField(blank=True, max_length=255)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("country_code", models.CharField(blank=True, max_length=2)),
                ("jurisdiction", models.CharField(blank=True, max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("incorporation_date", models.DateField(blank=True, null=True)),
                ("external_reference", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"indexes": [models.Index(fields=["party_type", "display_name"], name="compliance__party_t_7a2407_idx"), models.Index(fields=["country_code"], name="compliance__country_755679_idx")]},
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("policy_key", models.CharField(db_index=True, max_length=100)),
                ("version", models.CharField(max_length=50)),
                ("jurisdiction_scope", models.CharField(max_length=100)),
                ("subject_scope", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [models.Index(fields=["policy_key", "jurisdiction_scope"], name="compliance__policy__b5238b_idx")],
                "unique_together": {("policy_key", "version")},
            },
        ),
        migrations.CreateModel(
            name="ComplianceProfile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("current_state", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("IN_REVIEW", "In Review"), ("WAITING_FOR_APPLICANT", "Waiting For Applicant"), ("WAITING_FOR_VENDOR", "Waiting For Vendor"), ("ESCALATED", "Escalated"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("RESTRICTED", "Restricted"), ("EXPIRED", "Expired")], default="DRAFT", max_length=30)),
                ("current_risk_tier", models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("PROHIBITED", "Prohibited")], default="MEDIUM", max_length=20)),
                ("operability_blocked", models.BooleanField(db_index=True, default=True)),
                ("is_legacy_subject", models.BooleanField(db_index=True, default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("party", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="profiles", to="compliance.complianceparty")),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="compliance_profiles", to=settings.AUTH_USER_MODEL)),
            ],
            options={"indexes": [models.Index(fields=["current_state", "operability_blocked"], name="compliance__current_f92564_idx"), models.Index(fields=["is_legacy_subject"], name="compliance__is_lega_91a29b_idx")]},
        ),
        migrations.CreateModel(
            name="ComplianceCase",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("case_type", models.CharField(choices=[("INDIVIDUAL_KYC", "Individual KYC"), ("ENTITY_KYB", "Entity KYB"), ("UBO_KYC", "UBO KYC"), ("CONTROLLER_KYC", "Controller KYC"), ("ONGOING_MONITORING", "Ongoing Monitoring")], db_index=True, max_length=30)),
                ("state", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("IN_REVIEW", "In Review"), ("WAITING_FOR_APPLICANT", "Waiting For Applicant"), ("WAITING_FOR_VENDOR", "Waiting For Vendor"), ("ESCALATED", "Escalated"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("RESTRICTED", "Restricted"), ("EXPIRED", "Expired")], db_index=True, default="DRAFT", max_length=30)),
                ("risk_tier", models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("PROHIBITED", "Prohibited")], db_index=True, default="MEDIUM", max_length=20)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("policy_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cases", to="compliance.policyversion")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cases", to="compliance.complianceprofile")),
            ],
            options={"indexes": [models.Index(fields=["case_type", "state"], name="compliance__case_ty_a0cd90_idx"), models.Index(fields=["risk_tier", "state"], name="compliance__risk_ti_7db321_idx")]},
        ),
        migrations.CreateModel(
            name="ComplianceAuditEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="compliance_audit_events", to=settings.AUTH_USER_MODEL)),
                ("case", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to="compliance.compliancecase")),
                ("profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="audit_events", to="compliance.complianceprofile")),
            ],
            options={"indexes": [models.Index(fields=["event_type", "created_at"], name="compliance__event_t_c5db9d_idx")]},
        ),
        migrations.CreateModel(
            name="ComplianceRestriction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("restriction_type", models.CharField(choices=[("INVESTOR_OPERABILITY", "Investor Operability"), ("CAPITAL_ACTIVITY", "Capital Activity"), ("DISTRIBUTIONS", "Distributions"), ("TRANSFERS", "Transfers"), ("FULL_ACCOUNT_RESTRICTION", "Full Account Restriction")], db_index=True, max_length=40)),
                ("reason_code", models.CharField(db_index=True, max_length=100)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("lifted_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("case", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="restrictions", to="compliance.compliancecase")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="restrictions", to="compliance.complianceprofile")),
            ],
            options={"indexes": [models.Index(fields=["active", "restriction_type"], name="compliance__active_89e990_idx")]},
        ),
        migrations.CreateModel(
            name="EvidenceDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("document_type", models.CharField(max_length=100)),
                ("storage_mode", models.CharField(default="VENDOR_REFERENCE", max_length=30)),
                ("vendor_reference", models.CharField(blank=True, max_length=255)),
                ("storage_reference", models.CharField(blank=True, max_length=500)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evidence_documents", to="compliance.compliancecase")),
            ],
            options={"indexes": [models.Index(fields=["document_type"], name="compliance__documen_2ef19a_idx"), models.Index(fields=["expires_at"], name="compliance__expires_09b76f_idx")]},
        ),
        migrations.CreateModel(
            name="MonitoringEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(choices=[("PROFILE_CHANGE", "Profile Change"), ("OWNERSHIP_CHANGE", "Ownership Change"), ("CAPITAL_ACTIVITY", "Capital Activity"), ("TRANSFER_ACTIVITY", "Transfer Activity"), ("VENDOR_ALERT", "Vendor Alert"), ("DOCUMENT_EXPIRY", "Document Expiry"), ("PERIODIC_REVIEW_DUE", "Periodic Review Due")], db_index=True, max_length=40)),
                ("source", models.CharField(max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("triggered_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("case", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="monitoring_events", to="compliance.compliancecase")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="monitoring_events", to="compliance.complianceprofile")),
            ],
            options={"indexes": [models.Index(fields=["event_type", "processed_at"], name="compliance__event_t_40f4a4_idx")]},
        ),
        migrations.CreateModel(
            name="PartyRelationship",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("relationship_type", models.CharField(choices=[("BENEFICIAL_OWNER", "Beneficial Owner"), ("CONTROLLER", "Controller"), ("AUTHORIZED_SIGNER", "Authorized Signer"), ("DIRECTOR", "Director")], db_index=True, max_length=30)),
                ("ownership_percentage", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("control_notes", models.TextField(blank=True)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("from_party", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_relationships", to="compliance.complianceparty")),
                ("to_party", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="incoming_relationships", to="compliance.complianceparty")),
            ],
            options={"indexes": [models.Index(fields=["relationship_type"], name="compliance__relati_0930a8_idx")]},
        ),
        migrations.CreateModel(
            name="ReviewTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("task_type", models.CharField(choices=[("INITIAL_REVIEW", "Initial Review"), ("REQUEST_INFORMATION", "Request Information"), ("ESCALATION_REVIEW", "Escalation Review"), ("PERIODIC_REVIEW", "Periodic Review"), ("ALERT_REVIEW", "Alert Review")], db_index=True, max_length=30)),
                ("status", models.CharField(choices=[("OPEN", "Open"), ("IN_PROGRESS", "In Progress"), ("BLOCKED", "Blocked"), ("COMPLETED", "Completed"), ("CANCELED", "Canceled")], db_index=True, default="OPEN", max_length=20)),
                ("priority", models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("CRITICAL", "Critical")], db_index=True, default="MEDIUM", max_length=20)),
                ("sla_due_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="compliance_review_tasks", to=settings.AUTH_USER_MODEL)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="review_tasks", to="compliance.compliancecase")),
            ],
            options={"indexes": [models.Index(fields=["status", "priority"], name="compliance__status_060309_idx"), models.Index(fields=["sla_due_at"], name="compliance__sla_due_8c36fd_idx")]},
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("risk_tier", models.CharField(choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High"), ("PROHIBITED", "Prohibited")], db_index=True, max_length=20)),
                ("triggered_rules", models.JSONField(blank=True, default=list)),
                ("score_snapshot", models.JSONField(blank=True, default=dict)),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                ("assessed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="compliance_risk_assessments", to=settings.AUTH_USER_MODEL)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="risk_assessments", to="compliance.compliancecase")),
                ("policy_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="risk_assessments", to="compliance.policyversion")),
            ],
        ),
        migrations.CreateModel(
            name="VendorCase",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("vendor_name", models.CharField(choices=[("PRIMARY", "Primary Vendor")], default="PRIMARY", max_length=20)),
                ("external_case_id", models.CharField(db_index=True, max_length=255)),
                ("sync_status", models.CharField(choices=[("PENDING", "Pending"), ("IN_PROGRESS", "In Progress"), ("SYNCED", "Synced"), ("FAILED", "Failed")], db_index=True, default="PENDING", max_length=20)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="vendor_cases", to="compliance.compliancecase")),
            ],
            options={"unique_together": {("vendor_name", "external_case_id")}},
        ),
        migrations.CreateModel(
            name="CaseDecision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("decision_type", models.CharField(choices=[("APPROVE", "Approve"), ("REJECT", "Reject"), ("RESTRICT", "Restrict"), ("ESCALATE", "Escalate"), ("REQUEST_INFORMATION", "Request Information")], db_index=True, max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="compliance_case_decisions", to=settings.AUTH_USER_MODEL)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="decisions", to="compliance.compliancecase")),
                ("policy_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="case_decisions", to="compliance.policyversion")),
            ],
            options={"indexes": [models.Index(fields=["decision_type", "created_at"], name="compliance__decisi_5a11b7_idx")]},
        ),
        migrations.CreateModel(
            name="ScreeningCheck",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("check_type", models.CharField(choices=[("IDENTITY", "Identity"), ("BUSINESS", "Business"), ("SANCTIONS", "Sanctions"), ("PEP", "PEP"), ("ADVERSE_MEDIA", "Adverse Media"), ("DOCUMENT", "Document")], db_index=True, max_length=30)),
                ("outcome", models.CharField(choices=[("PENDING", "Pending"), ("PASSED", "Passed"), ("REVIEW", "Review"), ("FAILED", "Failed")], db_index=True, default="PENDING", max_length=20)),
                ("severity", models.CharField(choices=[("INFO", "Info"), ("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")], default="INFO", max_length=20)),
                ("vendor_reference", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="screening_checks", to="compliance.compliancecase")),
                ("vendor_case", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="screening_checks", to="compliance.vendorcase")),
            ],
            options={"indexes": [models.Index(fields=["check_type", "outcome"], name="compliance__check_t_b8ccdd_idx"), models.Index(fields=["severity"], name="compliance__severit_25ef1c_idx")]},
        ),
    ]

