# Generated by Django 6.0.2 on 2026-05-07 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstatePortfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='re_portfolios_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Real Estate Portfolio',
                'verbose_name_plural': 'Real Estate Portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateAssumptions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inception_date', models.DateField()),
                ('forecast_horizon', models.PositiveIntegerField(default=10, help_text='In years')),
                ('default_appreciation_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('default_rental_growth_rate', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('default_vacancy_rate', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('default_discount_rate', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('acquisition_fee_percentage', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('property_mgmt_fee_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('maintenance_percentage_of_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('selling_fee_percentage', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('active_scenario', models.CharField(choices=[('BASE', 'Base'), ('BULL', 'Bull'), ('BEAR', 'Bear')], default='BASE', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='real_estate.realestateportfolio')),
            ],
            options={
                'verbose_name': 'Real Estate Assumptions',
                'verbose_name_plural': 'Real Estate Assumptions',
            },
        ),
    ]
