# Generated by Django 6.0.2 on 2026-05-08 09:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('submarket', models.CharField(blank=True, max_length=255)),
                ('property_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('RETAIL', 'Retail'), ('MIXED_USE', 'Mixed-Use')], max_length=50)),
                ('financing_type', models.CharField(choices=[('ALL_CASH', 'All Cash'), ('MORTGAGED', 'Mortgaged'), ('MEZZANINE', 'Mezzanine')], max_length=50)),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('OFF_PLAN', 'Off-Plan')], default='HELD', max_length=20)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_operational_expenses', models.DecimalField(decimal_places=2, default=0.0, help_text='Annual expenses', max_digits=15)),
                ('acq_fee_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('appreciation_rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vacancy_rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='real_estate.realestateportfolio')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
