# Generated by Django 6.0.2 on 2026-05-11 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('base_interest_rate', models.DecimalField(decimal_places=2, help_text='Base interest rate as a percentage', max_digits=5)),
                ('tenor', models.PositiveIntegerField(help_text='Tenor in years')),
                ('payments_per_year', models.PositiveIntegerField(default=12)),
                ('loan_start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financing', to='real_estate.property')),
            ],
            options={
                'verbose_name': 'Financing Entry',
                'verbose_name_plural': 'Financing Entries',
            },
        ),
    ]
