# Generated by Django 6.0.2 on 2026-05-11 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_financingentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffPlanDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('construction_start_date', models.DateField()),
                ('expected_completion_date', models.DateField()),
                ('appreciation_rate_at_completion', models.DecimalField(decimal_places=2, default=25.0, help_text='Expected appreciation percentage at completion', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='off_plan_details', to='real_estate.property')),
            ],
            options={
                'verbose_name': 'Off-Plan Details',
                'verbose_name_plural': 'Off-Plan Details',
            },
        ),
        migrations.CreateModel(
            name='OffPlanMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('percentage_of_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='real_estate.property')),
            ],
            options={
                'verbose_name': 'Off-Plan Milestone',
                'verbose_name_plural': 'Off-Plan Milestones',
                'ordering': ['date'],
            },
        ),
    ]
