# Generated by Django 6.0.2 on 2026-05-11 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_offplandetails_offplanmilestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_date', models.DateField()),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('selling_fee_percentage', models.DecimalField(decimal_places=2, help_text='Selling fee as a percentage of selling price', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='real_estate.property')),
            ],
            options={
                'verbose_name': 'Property Sale',
                'verbose_name_plural': 'Property Sales',
                'ordering': ['-sale_date'],
            },
        ),
    ]
