# Generated by Django 6.0.2 on 2026-05-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_propertysale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('HELD', 'Held'), ('OFF_PLAN', 'Off-Plan'), ('SOLD', 'Sold')], default='HELD', max_length=20),
        ),
    ]
