# Generated by Django 6.0.2 on 2026-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_alter_property_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='offplandetails',
            name='sale_at_completion',
            field=models.BooleanField(default=False),
        ),
    ]
