# Generated by Django 6.0.2 on 2026-05-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0007_offplandetails_sale_at_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Size in square meters', max_digits=10),
        ),
    ]
