# Generated by Django 6.0.2 on 2026-05-14 03:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0008_property_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateportfolio',
            name='total_units',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=30),
        ),
        migrations.CreateModel(
            name='RealEstateInvestorAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PRIMARY_INVESTMENT', 'Primary Investment'), ('SECONDARY_INVESTMENT', 'Secondary Investment'), ('SECONDARY_EXIT', 'Secondary Exit')], max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('percentage_sold', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('units', models.DecimalField(decimal_places=4, default=0.0, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_investor_actions', to=settings.AUTH_USER_MODEL)),
                ('investor_selling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='re_investor_sales', to=settings.AUTH_USER_MODEL)),
                ('investor_sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='re_investor_purchases', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_actions', to='real_estate.realestateportfolio')),
            ],
            options={
                'ordering': ['year', 'created_at'],
                'indexes': [models.Index(fields=['investor', 'portfolio'], name='real_estate_investo_b5e569_idx'), models.Index(fields=['year'], name='real_estate_year_fcc3dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='RealEstateInvestorStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('capital_deployed', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('realized_gain', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('units', models.DecimalField(decimal_places=4, default=0.0, max_digits=30)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='re_investor_stats', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_stats', to='real_estate.realestateportfolio')),
            ],
            options={
                'ordering': ['amount_invested'],
                'indexes': [models.Index(fields=['investor', 'portfolio'], name='real_estate_investo_61eb8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RealEstatePossibleCapitalSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_capital_sources', to='real_estate.realestateportfolio')),
            ],
            options={
                'ordering': ['year', 'created_at'],
                'indexes': [models.Index(fields=['portfolio', 'year'], name='real_estate_portfol_7e53c5_idx')],
            },
        ),
    ]
