# Generated by Django 6.0.2 on 2026-05-16 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0009_realestateportfolio_total_units_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='financing_type',
            field=models.CharField(choices=[('ALL_CASH', 'All Cash'), ('MORTGAGED', 'Mortgaged'), ('MEZZANINE', 'Mezzanine'), ('PRIMARY_INSTALLMENTS', 'Primary Sales with Installments')], max_length=50),
        ),
        migrations.CreateModel(
            name='InstallmentEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tenor', models.PositiveIntegerField(help_text='Tenor in years')),
                ('payments_per_year', models.PositiveIntegerField(default=12)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment', to='real_estate.property')),
            ],
            options={
                'verbose_name': 'Installment Entry',
                'verbose_name_plural': 'Installment Entries',
            },
        ),
    ]
