# Generated by Django 6.0.2 on 2026-05-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0010_alter_property_financing_type_installmententry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('HELD', 'Held'), ('OFF_PLAN', 'Off-Plan'), ('SOLD', 'Sold'), ('USUFRUCT', 'Usufruct')], default='HELD', max_length=20),
        ),
    ]
