# Generated by Django 6.0.2 on 2026-05-20 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0011_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='UsufructDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('prep_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('outflow_monthly_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('annual_ops_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('inflow_monthly_rent', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('outflow_rent_appreciation_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('inflow_rent_appreciation_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usufruct_details', to='real_estate.property')),
            ],
            options={
                'verbose_name': 'Usufruct Details',
                'verbose_name_plural': 'Usufruct Details',
            },
        ),
    ]
