# Generated by Django 6.0.2 on 2026-05-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0012_alter_property_monthly_rent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('RETAIL', 'Retail'), ('MIXED_USE', 'Mixed-Use'), ('WAREHOUSE', 'Warehouses')], max_length=50),
        ),
    ]
