# Generated by Django 6.0.2 on 2026-05-20 11:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0013_alter_property_property_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='realestateinvestorstats',
            unique_together={('investor', 'portfolio')},
        ),
    ]
