# Generated by Django 6.0.2 on 2026-05-21 07:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0014_alter_realestateinvestorstats_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Jurisdiction',
                'verbose_name_plural': 'Jurisdictions',
            },
        ),
        migrations.AddField(
            model_name='usufructdetails',
            name='investor_role',
            field=models.CharField(choices=[('BARE_OWNER', 'Bare Owner'), ('USUFRUCT_HOLDER', 'Usufruct Holder')], default='USUFRUCT_HOLDER', max_length=20),
        ),
        migrations.AddField(
            model_name='realestateportfolio',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='real_estate.jurisdiction'),
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('ACQUISITION', 'Acquisition'), ('OWNERSHIP', 'Ownership'), ('INCOME', 'Income'), ('DISPOSAL', 'Disposal'), ('FINANCING', 'Financing')], max_length=20)),
                ('trigger', models.CharField(choices=[('CONTRACT_SIGNING', 'Contract Signing'), ('ON_PAYMENT', 'On Payment'), ('HANDOVER', 'Handover'), ('ANNUAL', 'Annual'), ('DISPOSAL', 'Disposal')], max_length=20)),
                ('tax_base', models.CharField(choices=[('MARKET_VALUE', 'Market Value'), ('ASSESSED_VALUE', 'Assessed Value'), ('NET_INCOME', 'Net Income'), ('LOAN_AMOUNT', 'Loan Amount'), ('FIXED', 'Fixed Amount')], max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Tax rate as a decimal (e.g. 0.05 for 5%)', max_digits=10)),
                ('valuation_ratio', models.DecimalField(decimal_places=2, default=1.0, help_text='Ratio of market value for assessed value', max_digits=5)),
                ('revaluation_freq', models.PositiveIntegerField(default=1, help_text='How often the assessment updates in years')),
                ('deductibility_cap', models.DecimalField(decimal_places=2, default=1.0, help_text='Cap on interest/expense deductions', max_digits=5)),
                ('lcf_limit', models.PositiveIntegerField(blank=True, help_text='Loss Carry Forward limit in years', null=True)),
                ('responsible_party', models.CharField(choices=[('BARE_OWNER', 'Bare Owner'), ('USUFRUCT_HOLDER', 'Usufruct Holder'), ('BOTH', 'Both / Not Applicable')], default='BOTH', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='real_estate.jurisdiction')),
            ],
            options={
                'verbose_name': 'Tax Rule',
                'verbose_name_plural': 'Tax Rules',
            },
        ),
    ]
