# Generated by Django 6.0.2 on 2026-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0015_jurisdiction_usufructdetails_investor_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateassumptions',
            name='default_depreciation_rate',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Annual depreciation rate as percentage', max_digits=5),
        ),
    ]
