# Generated by Django 6.0.2 on 2026-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0016_realestateassumptions_default_depreciation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], default='SECONDARY', max_length=20),
        ),
    ]
