# Generated by Django 6.0.2 on 2026-06-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0018_ledgeraccount_ledgertransaction_ledgerentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateportfolio',
            name='cover_image',
            field=models.URLField(blank=True, help_text="URL for the portfolio's background image", max_length=500, null=True),
        ),
    ]
