# Generated by Django 6.0.2 on 2026-06-05 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0019_realestateportfolio_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('DYNAMIC', 'Dynamic Portfolio Report'), ('ANNUAL', 'Annual Performance Report')], db_index=True, default='DYNAMIC', max_length=20)),
                ('config_json', models.JSONField(help_text='Metrics selection, chart types, sections, etc.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('GENERATING', 'Generating'), ('FAILED', 'Failed')], db_index=True, default='INACTIVE', max_length=20)),
                ('static_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='real_estate.realestateportfolio')),
            ],
            options={
                'verbose_name': 'Real Estate Report',
                'verbose_name_plural': 'Real Estate Reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='real_estate_slug_35bdfe_idx'), models.Index(fields=['status'], name='real_estate_status_cd5c6d_idx')],
            },
        ),
    ]
