# Generated by Django 6.0.2 on 2026-06-06 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0020_realestatereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateportfolio',
            name='report_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
