# Generated by Django 6.0.2 on 2026-06-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0021_realestateportfolio_report_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateportfolio',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='realestateportfolio',
            name='portfolio_lifecycle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='realestateportfolio',
            name='reasons_to_invest',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='realestateportfolio',
            name='strategy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='realestateportfolio',
            name='structure',
            field=models.TextField(blank=True),
        ),
    ]
