# Generated by Django 6.0.2 on 2026-06-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0022_realestateportfolio_overview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestateportfolio',
            name='cover_image',
            field=models.URLField(blank=True, help_text="URL for the portfolio's background image", max_length=1000, null=True),
        ),
    ]
