# Generated by Django 6.0.2 on 2026-06-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0023_alter_realestateportfolio_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestateassumptions',
            name='developer',
            field=models.CharField(blank=True, help_text='The developer of the portfolio', max_length=255),
        ),
    ]
