from django.urls import path

from compliance.api.views import (
    ComplianceAdminCaseApproveView,
    ComplianceAdminCaseDetailView,
    ComplianceAdminCaseEvidenceListCreateView,
    ComplianceAdminCaseListView,
    ComplianceAdminCaseRiskAssessmentCreateView,
    ComplianceAdminProfileListView,
    ComplianceAdminCaseSubmitVendorView,
    ComplianceAdminCaseAssignTaskView,
    ComplianceAdminProfileRescreenView,
    ComplianceAdminCaseRejectView,
    ComplianceAdminCaseRequestInformationView,
    ComplianceAdminCaseRestrictView,
    ComplianceAdminRestrictionLiftView,
    ComplianceAdminVendorCaseSyncView,
    ComplianceCaseDetailView,
    ComplianceHealthView,
    ComplianceReviewTaskListView,
    CurrentComplianceProfileView,
    EntityComplianceProfileCreateView,
    EntityRelationshipCreateView,
    MyComplianceCaseEvidenceListCreateView,
    MyComplianceCaseSubmitView,
    MyComplianceCasesView,
    PrimaryVendorWebhookView,
)

urlpatterns = [
    path("health/", ComplianceHealthView.as_view(), name="compliance-health"),
    path("me/", CurrentComplianceProfileView.as_view(), name="compliance-me"),
    path("my-cases/", MyComplianceCasesView.as_view(), name="compliance-my-cases"),
    path("cases/<uuid:case_id>/", ComplianceCaseDetailView.as_view(), name="compliance-case-detail"),
    path("cases/<uuid:case_id>/submit/", MyComplianceCaseSubmitView.as_view(), name="compliance-case-submit"),
    path("cases/<uuid:case_id>/evidence/", MyComplianceCaseEvidenceListCreateView.as_view(), name="compliance-case-evidence"),
    path("entities/", EntityComplianceProfileCreateView.as_view(), name="compliance-entity-create"),
    path("entities/<uuid:profile_id>/relationships/", EntityRelationshipCreateView.as_view(), name="compliance-entity-relationship-create"),
    path("admin/profiles/", ComplianceAdminProfileListView.as_view(), name="compliance-admin-profiles"),
    path("admin/cases/", ComplianceAdminCaseListView.as_view(), name="compliance-admin-cases"),
    path("admin/cases/<uuid:case_id>/", ComplianceAdminCaseDetailView.as_view(), name="compliance-admin-case-detail"),
    path("admin/cases/<uuid:case_id>/evidence/", ComplianceAdminCaseEvidenceListCreateView.as_view(), name="compliance-admin-case-evidence"),
    path("admin/cases/<uuid:case_id>/risk-assessments/", ComplianceAdminCaseRiskAssessmentCreateView.as_view(), name="compliance-admin-case-risk-assessment"),
    path("admin/cases/<uuid:case_id>/assign-task/", ComplianceAdminCaseAssignTaskView.as_view(), name="compliance-admin-case-assign-task"),
    path("admin/cases/<uuid:case_id>/request-information/", ComplianceAdminCaseRequestInformationView.as_view(), name="compliance-admin-case-request-information"),
    path("admin/cases/<uuid:case_id>/approve/", ComplianceAdminCaseApproveView.as_view(), name="compliance-admin-case-approve"),
    path("admin/cases/<uuid:case_id>/reject/", ComplianceAdminCaseRejectView.as_view(), name="compliance-admin-case-reject"),
    path("admin/cases/<uuid:case_id>/restrict/", ComplianceAdminCaseRestrictView.as_view(), name="compliance-admin-case-restrict"),
    path("admin/cases/<uuid:case_id>/submit-to-vendor/", ComplianceAdminCaseSubmitVendorView.as_view(), name="compliance-admin-case-submit-vendor"),
    path("admin/profiles/<uuid:profile_id>/rescreen/", ComplianceAdminProfileRescreenView.as_view(), name="compliance-admin-profile-rescreen"),
    path("admin/review-tasks/", ComplianceReviewTaskListView.as_view(), name="compliance-admin-review-tasks"),
    path("admin/vendor-cases/<uuid:vendor_case_id>/sync/", ComplianceAdminVendorCaseSyncView.as_view(), name="compliance-admin-vendor-case-sync"),
    path("admin/restrictions/<uuid:restriction_id>/lift/", ComplianceAdminRestrictionLiftView.as_view(), name="compliance-admin-restriction-lift"),
    path("vendor/webhooks/primary/", PrimaryVendorWebhookView.as_view(), name="compliance-primary-vendor-webhook"),
]
