# Generated by Django 6.0.2 on 2026-02-28 13:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('FUND_CREATED', 'Fund Created'), ('FUND_DEACTIVATED', 'Fund Deactivated'), ('FUND_INFO_UPDATED', 'Fund Information Updated'), ('FUND_INFO_UPDATE_FAILED', 'Fund Information Update Failed'), ('SC_MEMBER_ASSIGNED', 'SC Member Assigned'), ('INVESTOR_ASSIGNED', 'Investor Assigned')], db_index=True, max_length=50)),
                ('success', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_actions', to=settings.AUTH_USER_MODEL)),
                ('target_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='funds.fund')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['name'], name='funds_fund_name_9235d4_idx'),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['is_active'], name='funds_fund_is_acti_2c7b01_idx'),
        ),
        migrations.AddIndex(
            model_name='fundlog',
            index=models.Index(fields=['timestamp'], name='funds_fundl_timesta_c6f3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='fundlog',
            index=models.Index(fields=['action'], name='funds_fundl_action_b0dfd1_idx'),
        ),
    ]
