# Generated by Django 6.0.2 on 2026-03-04 11:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundlog',
            name='action',
            field=models.CharField(choices=[('FUND_CREATED', 'Fund Created'), ('FUND_DEACTIVATED', 'Fund Deactivated'), ('FUND_INFO_UPDATED', 'Fund Information Updated'), ('FUND_INFO_UPDATE_FAILED', 'Fund Information Update Failed'), ('MODEL_INPUTS_UPDATED', 'Model Inputs Updated'), ('DEAL_CREATED', 'Deal Created'), ('DEAL_UPDATED', 'Deal Updated'), ('DEAL_DELETED', 'Deal Deleted'), ('SC_MEMBER_ASSIGNED', 'SC Member Assigned'), ('INVESTOR_ASSIGNED', 'Investor Assigned'), ('ROLE_REMOVED', 'Role Removed')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='InvestmentDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_of_investment', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXITED', 'Exited')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='funds.fund')),
            ],
            options={
                'ordering': ['-date_of_investment'],
            },
        ),
        migrations.CreateModel(
            name='ModelInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_fund_size', models.DecimalField(decimal_places=2, default=100000000.0, max_digits=20)),
                ('fund_life', models.PositiveIntegerField(default=10)),
                ('investment_period', models.PositiveIntegerField(default=5)),
                ('exit_horizon', models.PositiveIntegerField(default=5)),
                ('min_investor_ticket', models.DecimalField(decimal_places=2, default=1000000.0, max_digits=20)),
                ('max_investor_ticket', models.DecimalField(decimal_places=2, default=5000000.0, max_digits=20)),
                ('lock_up_period', models.PositiveIntegerField(default=7)),
                ('preferred_return', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('management_fee', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('admin_cost', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('least_expected_moic_tier_1', models.DecimalField(decimal_places=2, default=1.5, max_digits=5)),
                ('least_expected_moic_tier_2', models.DecimalField(decimal_places=2, default=2.0, max_digits=5)),
                ('tier_1_carry', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('tier_2_carry', models.DecimalField(decimal_places=2, default=25.0, max_digits=5)),
                ('tier_3_carry', models.DecimalField(decimal_places=2, default=30.0, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_inputs', to='funds.fund')),
            ],
        ),
    ]
