# Generated by Django 6.0.2 on 2026-03-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_alter_fundlog_action_investmentdeal_modelinput'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentdeal',
            options={'ordering': ['-entry_year', 'company_name']},
        ),
        migrations.RemoveField(
            model_name='investmentdeal',
            name='date_of_investment',
        ),
        migrations.RemoveField(
            model_name='investmentdeal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='investmentdeal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='investmentdeal',
            name='status',
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='base_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='company_name',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='company_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='downside_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='entry_valuation',
            field=models.DecimalField(decimal_places=2, default=2021, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='entry_year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='exit_year',
            field=models.PositiveIntegerField(default=2029),
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='selected_scenario',
            field=models.CharField(choices=[('BASE', 'Base'), ('DOWNSIDE', 'Downside'), ('UPSIDE', 'Upside')], default='BASE', max_length=10),
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='upside_factor',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
