# Generated by Django 6.0.2 on 2026-03-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_alter_investmentdeal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinput',
            name='inception_year',
            field=models.PositiveIntegerField(default=2024),
        ),
    ]
