# Generated by Django 6.0.2 on 2026-03-17 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_modelinput_inception_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundlog',
            name='action',
            field=models.CharField(choices=[('FUND_CREATED', 'Fund Created'), ('FUND_DEACTIVATED', 'Fund Deactivated'), ('FUND_INFO_UPDATED', 'Fund Information Updated'), ('FUND_INFO_UPDATE_FAILED', 'Fund Information Update Failed'), ('MODEL_INPUTS_UPDATED', 'Model Inputs Updated'), ('DEAL_CREATED', 'Deal Created'), ('DEAL_UPDATED', 'Deal Updated'), ('DEAL_DELETED', 'Deal Deleted'), ('CURRENT_DEAL_CREATED', 'Current Deal Created'), ('CURRENT_DEAL_UPDATED', 'Current Deal Updated'), ('CURRENT_DEAL_DELETED', 'Current Deal Deleted'), ('SC_MEMBER_ASSIGNED', 'SC Member Assigned'), ('INVESTOR_ASSIGNED', 'Investor Assigned'), ('ROLE_REMOVED', 'Role Removed')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='CurrentDeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('entry_year', models.PositiveIntegerField(default=2024)),
                ('latest_valuation_year', models.PositiveIntegerField(default=2024)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=20)),
                ('entry_valuation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('latest_valuation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_deals', to='funds.fund')),
            ],
            options={
                'ordering': ['-entry_year', 'company_name'],
            },
        ),
    ]
