# Generated by Django 6.0.2 on 2026-03-22 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_alter_fundlog_action_currentdeal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fund',
            name='funds_fund_is_acti_2c7b01_idx',
        ),
        migrations.AddField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('ESTABLISHED', 'Active (Established)'), ('FUTURE', 'Active (Future)'), ('DEACTIVATED', 'Deactivated')], db_index=True, default='FUTURE', max_length=20),
        ),
        migrations.AlterField(
            model_name='fundlog',
            name='action',
            field=models.CharField(choices=[('FUND_CREATED', 'Fund Created'), ('FUND_STATUS_UPDATED', 'Fund Status Updated'), ('FUND_INFO_UPDATED', 'Fund Information Updated'), ('FUND_INFO_UPDATE_FAILED', 'Fund Information Update Failed'), ('MODEL_INPUTS_UPDATED', 'Model Inputs Updated'), ('DEAL_CREATED', 'Deal Created'), ('DEAL_UPDATED', 'Deal Updated'), ('DEAL_DELETED', 'Deal Deleted'), ('CURRENT_DEAL_CREATED', 'Current Deal Created'), ('CURRENT_DEAL_UPDATED', 'Current Deal Updated'), ('CURRENT_DEAL_DELETED', 'Current Deal Deleted'), ('SC_MEMBER_ASSIGNED', 'SC Member Assigned'), ('INVESTOR_ASSIGNED', 'Investor Assigned'), ('ROLE_REMOVED', 'Role Removed')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['status'], name='funds_fund_status_2dfe57_idx'),
        ),
        migrations.RemoveField(
            model_name='fund',
            name='is_active',
        ),
    ]
