# Generated by Django 6.0.2 on 2026-03-27 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_remove_fund_funds_fund_is_acti_2c7b01_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdeal',
            name='is_pro_rata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='parent_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_rata_deals', to='funds.investmentdeal'),
        ),
    ]
