# Generated by Django 6.0.2 on 2026-03-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_investmentdeal_is_pro_rata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentdeal',
            name='is_pro_rata',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='currentdeal',
            name='parent_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pro_rata_deals', to='funds.currentdeal'),
        ),
    ]
