# Generated by Django 6.0.2 on 2026-03-28 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0008_currentdeal_is_pro_rata_currentdeal_parent_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentdeal',
            name='pro_rata_rights',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentdeal',
            name='pro_rata_rights',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InvestmentRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('entry_valuation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('target_valuation', models.DecimalField(decimal_places=2, max_digits=20)),
                ('exercise_pro_rata', models.BooleanField(default=False)),
                ('amount_invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('new_ownership_percentage', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_rounds', to='funds.fund')),
            ],
            options={
                'ordering': ['year', 'created_at'],
            },
        ),
    ]
