# Generated by Django 6.0.2 on 2026-03-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0009_currentdeal_pro_rata_rights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentround',
            name='associated_deal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_round', to='funds.currentdeal'),
        ),
    ]
