# Generated by Django 6.0.2 on 2026-03-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0010_investmentround_associated_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentround',
            old_name='entry_valuation',
            new_name='new_money_raised',
        ),
        migrations.AddField(
            model_name='investmentround',
            name='pre_money_valuation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
