# Generated by Django 6.0.2 on 2026-03-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0011_rename_entry_valuation_investmentround_new_money_raised_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdeal',
            name='expected_number_of_rounds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
