# Generated by Django 6.0.2 on 2026-03-29 14:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0012_investmentdeal_expected_number_of_rounds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CAPITAL_INVESTMENT', 'Capital Investment'), ('SECONDARY_EXIT', 'Secondary Exit')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('exit_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_actions', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['year', 'created_at'],
                'indexes': [models.Index(fields=['investor', 'fund'], name='funds_inves_investo_432e0b_idx'), models.Index(fields=['year'], name='funds_inves_year_00bb9f_idx')],
            },
        ),
    ]
