# Generated by Django 6.0.2 on 2026-03-30 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0013_investoraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundlog',
            name='action',
            field=models.CharField(choices=[('FUND_CREATED', 'Fund Created'), ('FUND_STATUS_UPDATED', 'Fund Status Updated'), ('FUND_INFO_UPDATED', 'Fund Information Updated'), ('FUND_INFO_UPDATE_FAILED', 'Fund Information Update Failed'), ('MODEL_INPUTS_UPDATED', 'Model Inputs Updated'), ('DEAL_CREATED', 'Deal Created'), ('DEAL_UPDATED', 'Deal Updated'), ('DEAL_DELETED', 'Deal Deleted'), ('CURRENT_DEAL_CREATED', 'Current Deal Created'), ('CURRENT_DEAL_UPDATED', 'Current Deal Updated'), ('CURRENT_DEAL_DELETED', 'Current Deal Deleted'), ('SC_MEMBER_ASSIGNED', 'SC Member Assigned'), ('INVESTOR_ASSIGNED', 'Investor Assigned'), ('ROLE_REMOVED', 'Role Removed'), ('INVESTOR_ACTION_CREATED', 'Investor Action Created'), ('INVESTOR_ACTION_UPDATED', 'Investor Action Updated'), ('INVESTOR_ACTION_DELETED', 'Investor Action Deleted')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('execution_capacity_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('market_validation_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=4)),
                ('status', models.CharField(choices=[('MONETIZE', 'Monetize'), ('ON_TRACK', 'On-Track'), ('RESTRUCTURE', 'Restructure'), ('SHUTDOWN', 'Shutdown')], default='ON_TRACK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='funds.fund')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
                'unique_together': {('fund', 'company_name')},
            },
        ),
    ]
