# Generated by Django 6.0.2 on 2026-04-01 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0014_alter_fundlog_action_riskassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='total_units',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=30),
        ),
        migrations.AddField(
            model_name='investoraction',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='investoraction',
            name='investor_selling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investoraction',
            name='investor_sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investoraction',
            name='percentage_sold',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='investoraction',
            name='units',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='investoraction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investoraction',
            name='exit_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investoraction',
            name='original_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='investoraction',
            name='type',
            field=models.CharField(choices=[('PRIMARY_INVESTMENT', 'Primary Investment'), ('SECONDARY_INVESTMENT', 'Secondary Investment'), ('SECONDARY_EXIT', 'Secondary Exit')], max_length=30),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='execution_capacity_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='market_validation_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
