# Generated by Django 6.0.2 on 2026-04-03 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0016_fix_schema_inconsistency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentInvestorStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_invested', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('realized_gain', models.DecimalField(decimal_places=2, default=0.0, max_digits=30)),
                ('units', models.DecimalField(decimal_places=4, default=0.0, max_digits=30)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_investor_stats', to='funds.fund')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_investor_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['amount_invested'],
                'indexes': [models.Index(fields=['investor', 'fund'], name='funds_curre_investo_33b434_idx')],
            },
        ),
    ]
