# Generated by Django 6.0.2 on 2026-04-10 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0017_currentinvestorstats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='tag',
            field=models.CharField(choices=[('BIC', 'BIC'), ('VC', 'VC'), ('VS', 'VS'), ('AIG', 'AIG'), ('SF', 'SF'), ('REAL_ESTATE', 'Real estate')], db_index=True, default='VC', max_length=20),
        ),
        migrations.AlterField(
            model_name='currentinvestorstats',
            name='amount_invested',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AddIndex(
            model_name='fund',
            index=models.Index(fields=['tag'], name='funds_fund_tag_5ff2d0_idx'),
        ),
    ]
