# Generated by Django 6.0.2 on 2026-04-10 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0018_fund_tag_alter_currentinvestorstats_amount_invested_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleCapitalSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_capital_sources', to='funds.fund')),
            ],
            options={
                'ordering': ['year', 'created_at'],
                'indexes': [models.Index(fields=['fund', 'year'], name='funds_possi_fund_id_814b11_idx')],
            },
        ),
    ]
