# Generated by Django 6.0.2 on 2026-04-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0020_alter_investoraction_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investoraction',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='investoraction',
            name='percentage_sold',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
