# Generated by Django 6.0.2 on 2026-04-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0022_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentdeal',
            name='expected_exit_multiple',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
