# Generated by Django 6.0.2 on 2026-04-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0023_currentdeal_expected_exit_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentinvestorstats',
            name='capital_deployed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='currentdeal',
            name='expected_exit_multiple',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
    ]
