# Generated by Django 6.0.2 on 2026-04-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0024_currentinvestorstats_capital_deployed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='focus',
            field=models.CharField(blank=True, choices=[('GROWTH', 'Growth Focused'), ('YIELD', 'Yield Focused')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='reasons_to_invest',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fund',
            name='region',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fund',
            name='sharia_compliant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fund',
            name='strategy_and_fund_lifecycle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('DYNAMIC', 'Dynamic Fund Report'), ('CAPITAL_CALL', 'Capital Call Report')], db_index=True, default='DYNAMIC', max_length=20),
        ),
    ]
