# Generated by Django 6.0.2 on 2026-04-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0025_fund_focus_fund_overview_fund_reasons_to_invest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='cover_image',
            field=models.TextField(blank=True, help_text='Base64 encoded image or URL'),
        ),
    ]
