# Generated by Django 6.0.2 on 2026-04-14 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0026_fund_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='cover_image',
        ),
    ]
