# Generated by Django 6.0.2 on 2026-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0027_remove_fund_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='strategy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='structure',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modelinput',
            name='break_even_rate',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='modelinput',
            name='dilution_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='modelinput',
            name='failure_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='modelinput',
            name='high_growth_rate',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
    ]
