# Generated by Django 6.0.2 on 2026-04-18 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0028_fund_strategy_fund_structure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INVESTMENT', 'Investment'), ('LIQUIDATION', 'Liquidation')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('liquidation_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('units_to_sell', models.DecimalField(blank=True, decimal_places=4, max_digits=30, null=True)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_requests', to='funds.fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
