# Generated by Django 6.0.2 on 2026-05-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0029_investorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='report_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fund',
            name='target_appreciation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='fund',
            name='target_capital_allocation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fund',
            name='target_yield',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
