# Generated by Django 6.0.2 on 2026-05-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0030_fund_report_config_fund_target_appreciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='investment_composition',
            field=models.JSONField(blank=True, default=list, help_text='Customizable investment composition (e.g. Ventures vs SMEs)'),
        ),
        migrations.AddField(
            model_name='fund',
            name='risk_measures',
            field=models.JSONField(blank=True, default=list, help_text='Structured list of risk measures with title and description'),
        ),
    ]
