# Generated by Django 6.0.2 on 2026-05-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0031_fund_investment_composition_fund_risk_measures'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdeal',
            name='investment_type',
            field=models.CharField(choices=[('EQUITY', 'Equity Financing'), ('VENTURE_DEBT', 'Venture Debt'), ('VENTURE_DEBT_ROYALTIES', 'Venture Debt with Royalties (Shariah Compliant)')], default='EQUITY', max_length=50),
        ),
    ]
