# Generated by Django 6.0.2 on 2026-05-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0032_investmentdeal_investment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='tag',
            field=models.CharField(choices=[('BIC', 'BIC'), ('VC', 'VC'), ('VS', 'VS'), ('AIG', 'AIG'), ('SF', 'SF')], db_index=True, default='VC', max_length=20),
        ),
    ]
