# Generated by Django 6.0.2 on 2026-05-15 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0033_alter_fund_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundlog',
            name='action',
            field=models.CharField(choices=[('FUND_CREATED', 'Fund Created'), ('FUND_STATUS_UPDATED', 'Fund Status Updated'), ('FUND_INFO_UPDATED', 'Fund Information Updated'), ('FUND_INFO_UPDATE_FAILED', 'Fund Information Update Failed'), ('MODEL_INPUTS_UPDATED', 'Model Inputs Updated'), ('DEAL_CREATED', 'Deal Created'), ('DEAL_UPDATED', 'Deal Updated'), ('DEAL_DELETED', 'Deal Deleted'), ('CURRENT_DEAL_CREATED', 'Current Deal Created'), ('CURRENT_DEAL_UPDATED', 'Current Deal Updated'), ('CURRENT_DEAL_DELETED', 'Current Deal Deleted'), ('SC_MEMBER_ASSIGNED', 'SC Member Assigned'), ('INVESTOR_ASSIGNED', 'Investor Assigned'), ('ROLE_REMOVED', 'Role Removed'), ('INVESTOR_ACTION_CREATED', 'Investor Action Created'), ('INVESTOR_ACTION_UPDATED', 'Investor Action Updated'), ('INVESTOR_ACTION_DELETED', 'Investor Action Deleted'), ('DISTRIBUTION_CREATED', 'Distribution Created'), ('DISTRIBUTION_UPDATED', 'Distribution Updated'), ('DISTRIBUTION_DELETED', 'Distribution Deleted')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('EXIT_PROCEED', 'Exit Proceed'), ('DIVIDEND', 'Dividend / Yield')], default='EXIT_PROCEED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='funds.currentdeal')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='funds.fund')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
