# Generated by Django 6.0.2 on 2026-06-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0034_alter_fundlog_action_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='default_dividend_treatment',
            field=models.CharField(choices=[('CASH', 'Cash Payout'), ('REINVEST', 'REINVESTMENT (DRIP)')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='fund',
            name='dividend_frequency',
            field=models.CharField(choices=[('QUARTERLY', 'Quarterly'), ('BI_ANNUAL', 'Bi-Annual'), ('ANNUAL', 'Annual')], default='ANNUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='investoraction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investoraction',
            name='type',
            field=models.CharField(choices=[('PRIMARY_INVESTMENT', 'Primary Investment'), ('SECONDARY_INVESTMENT', 'Secondary Investment'), ('SECONDARY_EXIT', 'Secondary Exit'), ('DIVIDEND_PAYOUT', 'Dividend Payout (Cash)'), ('DIVIDEND_REINVESTMENT', 'Dividend Reinvestment')], max_length=30),
        ),
    ]
