# Generated by Django 6.0.2 on 2026-06-14 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0035_fund_default_dividend_treatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investoraction',
            name='distribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investor_actions', to='funds.distribution'),
        ),
    ]
