# Generated by Django 6.0.2 on 2026-06-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0036_investoraction_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investoraction',
            name='type',
            field=models.CharField(choices=[('PRIMARY_INVESTMENT', 'Primary Investment'), ('SECONDARY_INVESTMENT', 'Secondary Investment'), ('SECONDARY_EXIT', 'Secondary Exit'), ('DIVIDEND_PAYOUT', 'Dividend Payout (Cash)'), ('DIVIDEND_REINVESTMENT', 'Dividend Reinvestment'), ('EXIT_PAYOUT', 'Exit Payout (Cash)'), ('EXIT_REINVESTMENT', 'Exit Reinvestment')], max_length=30),
        ),
    ]
