# Generated by Django 6.0.2 on 2026-02-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_assign_super_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_APPROVED', 'User Approved'), ('USER_SOFT_DELETED', 'User Soft Deleted'), ('ROLE_ASSIGNED', 'Role Assigned'), ('ROLE_REMOVED', 'Role Removed'), ('FUND_CREATED', 'Fund Created'), ('ACCESS_DENIED', 'Access Denied'), ('UNAUTHENTICATED_ACCESS_DENIED', 'Unauthenticated Access Denied')], db_index=True, max_length=50),
        ),
    ]
