# Generated by Django 6.0.2 on 2026-02-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
        ('users', '0007_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.fund'),
        ),
        migrations.AlterField(
            model_name='userroleassignment',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='funds.fund'),
        ),
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
