# Generated by Django 6.0.2 on 2026-02-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_auditlog_fund_alter_userroleassignment_fund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_APPROVED', 'User Approved'), ('USER_SOFT_DELETED', 'User Soft Deleted'), ('ROLE_ASSIGNED', 'Role Assigned'), ('ROLE_REMOVED', 'Role Removed'), ('FUND_CREATED', 'Fund Created'), ('FUND_DEACTIVATED', 'Fund Deactivated'), ('FUND_INFO_UPDATED', 'Fund Information Updated'), ('FUND_INFO_UPDATE_FAILED', 'Fund Information Update Failed'), ('ACCESS_DENIED', 'Access Denied'), ('UNAUTHENTICATED_ACCESS_DENIED', 'Unauthenticated Access Denied'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed')], db_index=True, max_length=50),
        ),
    ]
