# Generated by Django 6.0.2 on 2026-04-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('USER_APPROVED', 'User Approved'), ('USER_SOFT_DELETED', 'User Soft Deleted'), ('ROLE_ASSIGNED', 'Role Assigned'), ('ROLE_REMOVED', 'Role Removed'), ('FUND_CREATED', 'Fund Created'), ('FUND_DEACTIVATED', 'Fund Deactivated'), ('FUND_INFO_UPDATED', 'Fund Information Updated'), ('FUND_INFO_UPDATE_FAILED', 'Fund Information Update Failed'), ('MODEL_INPUTS_UPDATED', 'Model Inputs Updated'), ('DEAL_CREATED', 'Deal Created'), ('DEAL_UPDATED', 'Deal Updated'), ('DEAL_DELETED', 'Deal Deleted'), ('REPORT_CREATED', 'Report Created'), ('REPORT_UPDATED', 'Report Updated'), ('REPORT_DELETED', 'Report Deleted'), ('REPORT_GENERATED', 'Report Generated'), ('ACCESS_DENIED', 'Access Denied'), ('UNAUTHENTICATED_ACCESS_DENIED', 'Unauthenticated Access Denied'), ('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('PASSWORD_RESET', 'Password Reset')], db_index=True, max_length=50),
        ),
    ]
