# Generated by Django 6.0.2 on 2026-05-08 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0033_alter_fund_tag'),
        ('real_estate', '0002_property'),
        ('users', '0013_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userroleassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userroleassignment',
            name='real_estate_portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='real_estate.realestateportfolio'),
        ),
        migrations.AlterUniqueTogether(
            name='userroleassignment',
            unique_together={('user', 'role', 'fund', 'real_estate_portfolio')},
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['user', 'real_estate_portfolio'], name='users_userr_user_id_58076b_idx'),
        ),
        migrations.AddIndex(
            model_name='userroleassignment',
            index=models.Index(fields=['role', 'real_estate_portfolio'], name='users_userr_role_id_463cc2_idx'),
        ),
    ]
