# Generated by Django 6.0.2 on 2026-06-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_seed_portfolio_manager_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroleassignment',
            name='dividend_treatment',
            field=models.CharField(choices=[('CASH', 'Cash Payout'), ('REINVEST', 'Reinvestment (DRIP)'), ('DEFAULT', 'Follow Fund Default')], default='DEFAULT', max_length=20),
        ),
    ]
